version: '3.8'
services:
  express-backend:
    build: ./backend
    container_name: express-backend
    ports:
      - '4000:4000'
    volumes:
      - ./express-backend:/app
      - ./app/node_modules
  react-frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - '5000:5000'
    volumes:
      - ./react-frontend:/app
      - ./app/node_modules
