name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build --if-present
      - run: npm test

  push_to_registry:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # build docker image and push to docker hub
    # only if the app build and test successfully
    needs: [ build_test ]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        working-directory: ./frontend
        with:
          push: true # Will only build if this is not here
          tags: |
                  ghcr.io/exchange-a-gram-front:${{ github.ref }}
                  ghcr.io/exchange-a-gram-front:latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        working-directory: ./backend
        with:
            push: true # Will only build if this is not here
            tags: |
                  ghcr.io/exchange-a-gram-back:${{ github.ref }}
                  ghcr.io/exchange-a-gram-back:latest
